const router = require("express").Router();

const healthRoutes = require("./healthRoutes");
const authRoutes = require("./authRoutes");
const scanRoutes = require("./scanRoutes");
const configScanRoutes = require("./configScanRoutes");
const secretScanRoutes = require("./secretScanRoutes");
const cipherScanRoutes = require("./cipherScanRoutes");
const cipherAssetRoutes = require("./cipherAssetRoutes");
const riskRoutes = require("./riskRoutes");
const githubRoutes = require("./githubRoutes");
const agentRoutes = require("./agentRoutes");
const scheduledScanRoutes = require("./scheduledScanRoutes");
const dashboardRoutes = require("./dashboardRoutes");
const webhookRoutes = require("./webhookRoutes");
const advisoryRoutes = require("./advisoryRoutes");
const containerScanRoutes = require("./containerScanRoutes");
const iacScanRoutes = require("./iacScanRoutes");
const findingRoutes = require("./findingRoutes");
const auditRoutes = require("./auditRoutes");
const quarantineRoutes = require("./quarantineRoutes");
const explainRoutes = require("./explainRoutes");
const chatRoutes = require("./chatRoutes");

const proxyRoutes = require("./proxyRoutes");
const edrRoutes = require("./edrRoutes");

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/scans", scanRoutes);
router.use("/config-scans", configScanRoutes);
router.use("/secret-scans", secretScanRoutes);
router.use("/cipher-scans", cipherScanRoutes);
router.use("/cipher-assets", cipherAssetRoutes);
router.use("/risk", riskRoutes);
router.use("/github", githubRoutes);
router.use("/agents", agentRoutes);
router.use("/scheduled-scans", scheduledScanRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/webhooks", webhookRoutes);
router.use("/advisories", advisoryRoutes);
router.use("/container-scans", containerScanRoutes);
router.use("/iac-scans", iacScanRoutes);
router.use("/findings", findingRoutes);
router.use("/audit", auditRoutes);
router.use("/quarantine", quarantineRoutes);
router.use("/explain", explainRoutes);
router.use("/chat", chatRoutes);
router.use("/proxy", proxyRoutes);
router.use("/edr", edrRoutes);

module.exports = router;
